//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuggerOff.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttachment
    {
        public int id { get; set; }
        public int TicketID { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public string Description { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
